version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - BIND_ADDRESS=0.0.0.0:3000
      - DATABASE_URL=sqlite:///data/knowflow.db
    volumes:
      - backend-data:/data
    ports:
      - "3000:3000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://backend:3000}
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://backend:3000}

volumes:
  backend-data:
