version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - BIND_ADDRESS=0.0.0.0:3000
      - DATABASE_URL=sqlite:///data/knowflow.db
    volumes:
      - backend-data:/data
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        EXPO_PUBLIC_API_BASE_URL: ${EXPO_PUBLIC_API_BASE_URL:-/api}
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  backend-data:
